apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-auth
  template:
    metadata:
      labels:
        app: ticketing-auth
    spec:
      containers:
        - name: ticketing-auth
          image: xenjaya/ticketing-auth
          env:
            - name: MONGO_URI
              value: 'mongodb://ticketing-auth-mongo-srv:27017/ticketing-auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: COOKIE_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SIGNING_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-auth-srv
spec:
  selector:
    app: ticketing-auth
  ports:
    - name: ticketing-auth
      protocol: TCP
      port: 3000
      targetPort: 3000
